# -*- coding: utf-8 -*-
"""python Bootcamp assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReRbcz-J2MGw5--F9KUHpNxzfa-cdLGt

Name : Azizur Rahman

**Question 1** Variables and Data Types
"""

#Question A
name = "Azizur Rahman"
age = 21
GPA = 3.54
student = True
print(type(name))
print(type(age))
print(type(GPA))
print(type(student))

#Question B

a = "123"
print(type(a))
change_a = int(a)
print(type(change_a))
b = 456
print(type(b))
change_b = str(b)
print(type(change_b))
c = 3.99
print(type(c))
change_c = int(c) #take the Floor value
print(type(change_c))
d = bool(1)
e = bool(0)
print(type(d))
print(type(e))

"""**Question 2** Operators"""

a = 17
b = 5

print("addition:",a + b) #arithmetic Operations
print("subtraction:",a - b)
print("multiplication:",a * b)
print("division:",a / b)

print("floor division:",a // b) #division and modulus
print("modulus:",a % b)

print("17 power of 5 : ", 17**5) #power

print("17 > 5:", a > b) #comparison
print("17 == 5:", a == b)
print("17 != 5:", a != b)

"""**Question 3** String Manipulation"""

# Question a
name = "python programming"
print(name.upper())#upper case
print(name.title())#title case
print(name.replace("programming","language")) #use replace keyword
print(len(name)) #length of name/string

#Question B
name = "Azizur Rahman"
age = 21
GPA = 3.54
print(f"My name is {name},I am {age} years old,and my GPA is {GPA}")

"""**Question 4** Conditional Statements - Intermediate"""

#Question A
age = int(input("enter you age :"))
if age < 0:
  print("Invalid age")
elif age > 18:
    print("You are an adult")
elif age >= 13 and age <= 17:
  print("You are a teenager")
elif age < 13:
    print("You are a Child")

#Question B - Even / Odd check
num = int(input("Enter a number: "))
print("Even" if num % 2 == 0 else "Odd")

#Question c - Grade Calculator

mark = int(input("Enter your mark: "))
if mark < 0 or mark > 100:
    print("Invalid mark")
elif mark >= 90:
    print("A+")
elif mark >= 80:
    print("A")
elif mark >= 70:
    print("B")
elif mark >= 60:
    print("C")
elif mark >= 50:
    print("D")
else:
    print("F — Failed")

#Question d - Login System

correct_username = "admin"
correct_password = "1234"

attempts = 0

while attempts < 3:
    username = input("Enter username: ")
    password = input("Enter password: ")

    if username == correct_username and password == correct_password:
        print("Login successful! Welcome,", username)
        break

    elif username == correct_username and password != correct_password:
        print("Incorrect password. Try again.")

    else:
        print("User not found.")

    attempts += 1

if attempts == 3:
    print("Account locked.")

"""**Question 5** ATM Simulation — Extend the Program"""

#Question A

pinNumber = 1234     # Correct PIN
balance = 5000      # Account balance

userPin = int(input("Enter PIN: "))

if userPin != pinNumber:
    print("Wrong PIN!")
else:
    request = float(input("Enter withdrawal amount: "))

    if request <= 500:
        print("Amount must be greater than 500")
    elif request > balance:
        print("Insufficient balance")
    else:
        balance = balance - request
        print("Successful withdrawal")
        print("Remaining balance:", balance)

#Question B


pinNumber = 1234
balance = 5000
attempts = 3
status = True

while attempts > 0:
    userPin = int(input("Enter PIN: "))

    if userPin == pinNumber:
        print("PIN correct!")

        request = float(input("Enter withdrawal amount: "))

        if request <= 500:
            print("Amount must be greater than 500")

        elif request > balance:
            print("Insufficient balance")

        else:
            balance = balance - request
            print("Withdrawal successful")
            print("Remaining balance:", balance)

        break
    else:
        attempts -= 1

        if attempts == 0:
            print("Card blocked!")
            status = False
        else:
          print("Wrong pin. Attempts remaining:", attempts)

#Question C

correct_username = "Azizur"
correct_password = "1234"
is_active = True
attempts = 3

while attempts > 0:

    username = input("Enter username: ")
    password = input("Enter password: ")

    if is_active == False:
        print("Account is disabled.")
        break

    elif username != correct_username or password != correct_password:
        attempts -= 1
        print("Login failed. Attempts left:", attempts)

    else:
        print("Login successful!")
        break

if attempts == 0:
    print("Account disabled.")

"""**Question 6** Basic Loops"""

#Question A
#print numbers
for i in range(1, 21):
    print(i)
#multiplication table of 7
print ("Multiplication table of 7")
for i in range (1 , 11):
  print("7 x",i,"=",7*i)
#print the sum of all numbers from 1 to 100
total = 0
for i in range(1,101):
  total += i
print("The sum of all numbers from 1 to 100 is:",total)
#print all even numbers between 1 and 50 using range()
for i in range(2,51):
  if(i % 2 == 0):
    print(i)
#practice list
fruits = ['apple', 'banana', 'cherry', 'mango', 'grape']
for i in range(len(fruits)):
  print(i + 1,":", fruits[i])

#Question B

#print numbers from 10 down to 1 using a while loop
x = 10
while x :
  print(x)
  x -=1

#enter positive numbers and calculate sum

total = 0
while True:
  num = int(input("Enter a positive number : "))

  if num <= 0 or num % 2 != 0:
    break
  total += num

print("total sum = ",total)

# Simulate a countdown: start from 10, print each number, then print 'Blast off!' when it reaches 0
y = 10
while y :
  print(y)
  y -= 1
print("Blast off!")
# Find and print the first 10 multiples of 6 using a while loop

count = 1

while count <= 10:
    print(6 * count)
    count += 1